resume_from_checkpoint_path: null
result_path: "./result"
pretrained_model_name_or_path: "naver-clova-ix/donut-base"
dataset_name_or_paths: ["jfargus/w9_cord_all_fields"]
sort_json_key: true
train_batch_sizes: [6]
val_batch_sizes: [1]
input_size: [960, 640]
max_length: 128
align_long_axis: false
num_nodes: 1
seed: 88
lr: 3e-5
warmup_steps: 300
max_epochs: 5
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
verbose: true
task_name: "w9_cord"
limit_val_batches: 0.25
num_training_samples_per_epoch: 1000
augment: true
augment_prob: 0.8
pretrained_branch: "main"
